version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: lb-mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  # app:
  #   build: .
  #   container_name: lb-container
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mongodb
  #   environment:
  #     MONGODB_URL: mongodb://admin:password@mongodb:27017/load-balancing-test

volumes:
  mongo_data:
    driver: local
