version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: db-mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: lb-container
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    env_file:
      - ./.env

volumes:
  mongo_data:
